### ISSUE TITLE
[Bug Report]: EntityDamageEvent

### ISSUE THREAD

**Issue by mewzuni** [Crazy-Crew/CrazyVouchers#42]
### Server Version

1.20.4

### Server Platform

Paper

### Describe the bug

It keeps spamming in my console :<

[02:45:18 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyVouchers v3.2.4
java.lang.NoSuchMethodError: 'org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource()'
        at com.badbones69.crazyvouchers.listeners.FireworkDamageListener.onFireworkDamage(FireworkDamageListener.java:15) ~[CrazyVouchers-3.2.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor329.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-397]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:265) ~[paper-1.20.4.jar:git-Paper-397]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1252) ~[paper-1.20.4.jar:git-Paper-397]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1107) ~[paper-1.20.4.jar:git-Paper-397]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[paper-1.20.4.jar:git-Paper-397]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1286) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2221) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:417) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1349) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2769) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2693) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1451) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1351) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1329) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.20.4.jar:git-Paper-397]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-397]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Crate Type

None

### Steps to reproduce

None. I'm just using Paper 1.20.4

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
You need to update from Build #397 to at least Build #423 or higher. 

https://papermc.io/downloads/paper
