### ISSUE TITLE
[Bug] Console Spam

### ISSUE THREAD

**Issue by elkoyofficial** [Crazy-Crew/CrazyVouchers#77]
### Plugin Version

1.21.1-40

### Server Version

1.20.1

### Server Platform

Spigot

### Describe the bug

Every time you right click anything in the server it spams the console with https://pastebin.com/0J4yHSiT

### Steps to reproduce

Right click anything in-game.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
ItemStack can't be null/air/amount of 0!

**Comment by ryderbelserion** [comment]
Try build 41 whenever it builds, just told nbt-api to shut up.

**Comment by elkoyofficial** [comment]
> Try build 41 whenever it builds, just told nbt-api to shut up. opinionated "errors" about how the game should work are the bane of my existence.

This worked. Thank you. :)

**Comment by ryderbelserion** [comment]
All the other vouchers still work? I made other small changes.

**Comment by elkoyofficial** [comment]
Actually seems to be back again.
[14:33:42 ERROR]: Could not pass event PlayerInteractEntityEvent to CrazyVouchers v1.21.1-41
java.lang.NullPointerException: ItemStack can't be null/air/amount of 0! This is not a NBTAPI bug!
        at CrazyVouchers-1.21.1-41.jar/libs.de.tr7zw.changeme.nbtapi.NBTItem.<init>(NBTItem.java:88) ~[CrazyVouchers-1.21.1-41.jar:?]
        at CrazyVouchers-1.21.1-41.jar/libs.de.tr7zw.changeme.nbtapi.NBTItem.<init>(NBTItem.java:44) ~[CrazyVouchers-1.21.1-41.jar:?]
        at CrazyVouchers-1.21.1-41.jar/com.badbones69.crazyvouchers.api.CrazyManager.getVoucherFromItem(CrazyManager.java:175) ~[CrazyVouchers-1.21.1-41.jar:?]
        at CrazyVouchers-1.21.1-41.jar/com.badbones69.crazyvouchers.listeners.VoucherClickListener.onArmorStandClick(VoucherClickListener.java:158) ~[CrazyVouchers-1.21.1-41.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1337.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2881) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onInteraction(ServerGamePacketListenerImpl.java:2931) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2870) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ryderbelserion** [comment]
Try again
